### ISSUE TITLE
React useState and useEffect

### ISSUE THREAD

**Issue by Rickal-Hamailton** [JackZheng10/Thought-Wall#1]
Hi, can you add a react example of using react hooks. working with reducers, actions and store,
i am not sure how to pass the updated data into my stores 

example.
```
 socket.on("newTicket", (ticket) => {
      this.setState({ userTickets : [...this.state.userTickets , ticket] });
    });
 const userTicketList = useSelector((state) => state.userTicketList)
  const { loading, error, userTickets } = userTicketList
```
how would i push the updated data into userTickets, i know the example above is absolutely incorrect

**Comment by JackZheng10** [comment]
It's been a while since I've worked with Redux so I'm not exactly sure, but you could always ask on another forum like StackOverflow. It seems to be a simple issue of passing the new ticket to your current tickets. 

Your syntax is correct with regards to this demo - when a newTicket event is received it will take the ticket passed in and append it to the userTickets array in your state.

**Comment by Rickal-Hamailton** [comment]
Thanks
